### ISSUE TITLE
Allow omission of [ and ]

### ISSUE THREAD

**Issue by williamhatcher** [Zerthick/SayItem#2]
Enclosing the item with [ and ] is not always desirable. Could you add a way to easily remove that, or modify the character?

```java
// Build the item text with the color
return Text.builder().color(itemColor)
        .append(Text.of("["), displayName, Text.of("]"))
        .onHover(TextActions.showItem(itemStack.createSnapshot())).build();
```

**Comment by AuWiMo** [comment]
@Zerthick 
I need this too! 

Is what @williamhatcher all the code you need to put in the plugin to make this work?

**Comment by williamhatcher** [comment]
I don’t remember if that was modified code or just the section that needed to be changed
